### ISSUE TITLE
Cannot read property of uuid

### ISSUE THREAD

**Issue by derMick** [maddox/magic-cards#46]
I am using the docker installation, did the whole config, have 2 cards for testing but no reaction on my Sonos system.
The docker log is showing the following, can anyone help me please?

###
magic-cards       | [1] Read Card ID: 0123456789
magic-cards       | [1] Finding card...
magic-cards       | [1] Found card: Spotify album xyz. Processing...
magic-cards       | [1] Processing action: Sonos
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kitchen/repeat/all
magic-cards       | [1] Calling: http://127.0.0.1:5005/zones
magic-cards       | [1] (node:72) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uuid' of undefined
magic-cards       | [1]     at SonosAction.forcePlaylistPlayback (/usr/src/app/scanner/actions/SonosAction.js:59:70)
magic-cards       | [1]     at <anonymous>
magic-cards       | [1]     at process._tickCallback (internal/process/next_tick.js:182:7)
magic-cards       | [1] (node:72) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
magic-cards       | [1] (node:72) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
###

Thanks for your help,

Regards derMick

**Comment by derMick** [comment]
Ok, problem found. I had to translate the Sonos room names into the my selected language of the Sonos system...
